#!/bin/bash
SERVER=/usr/bin/udpserver
if [ ! -e $SERVER ];then
	exit 1
fi
case "$1" in
	start)
		if [ -n "`pidof $SERVER`" ];then
			echo "Udpserver is running......"
		else
			$SERVER
		fi
	;;

	stop)
		PID=`pidof /usr/bin/udpserver`
		[ -n "$PID" ] && kill -9 $PID
	;;

	restart)
		PID=`pidof $SERVER`
		[ -n "$PID" ] && kill -9 $PID
		$SERVER
	;;

	*)
		exit 1
	;;

esac
